

CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NOT NULL,
	[Alias] [varchar](20) NOT NULL,
	[Enabled] [bit] NOT NULL,
	[SystemRoleID] [int] NOT NULL,
 CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_SystemRole] FOREIGN KEY([SystemRoleID])
REFERENCES [dbo].[SystemRole] ([ID])
GO

ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_SystemRole]
GO

